/*
 * Klarna Payments API V1
 * The payments API is used to create a session to offer Klarna's payment methods as part of your checkout. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).  **Note:** Examples provided in this section includes full payloads, including all supported fields , required and optionals. In order to implement a best in class request we recommend you don't include customer details when initiating a payment session. Refer to [Initiate a payment](https://docs.klarna.com/klarna-payments/integrate-with-klarna-payments/step-1-initiate-a-payment/) section for further details.  Read more on [Klarna payments](https://docs.klarna.com/klarna-payments/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Customer
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Customer {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_DATE_OF_BIRTH = "date_of_birth";
  @SerializedName(SERIALIZED_NAME_DATE_OF_BIRTH)
  private String dateOfBirth;

  public static final String SERIALIZED_NAME_GENDER = "gender";
  @SerializedName(SERIALIZED_NAME_GENDER)
  private String gender;

  public static final String SERIALIZED_NAME_LAST_FOUR_SSN = "last_four_ssn";
  @SerializedName(SERIALIZED_NAME_LAST_FOUR_SSN)
  private String lastFourSsn;

  public static final String SERIALIZED_NAME_NATIONAL_IDENTIFICATION_NUMBER = "national_identification_number";
  @SerializedName(SERIALIZED_NAME_NATIONAL_IDENTIFICATION_NUMBER)
  private String nationalIdentificationNumber;

  /**
   * Organization entity type. Only applicable for B2B customers.
   */
  @JsonAdapter(OrganizationEntityTypeEnum.Adapter.class)
 public enum OrganizationEntityTypeEnum {
    LIMITED_COMPANY("LIMITED_COMPANY"),
    
    PUBLIC_LIMITED_COMPANY("PUBLIC_LIMITED_COMPANY"),
    
    ENTREPRENEURIAL_COMPANY("ENTREPRENEURIAL_COMPANY"),
    
    LIMITED_PARTNERSHIP_LIMITED_COMPANY("LIMITED_PARTNERSHIP_LIMITED_COMPANY"),
    
    LIMITED_PARTNERSHIP("LIMITED_PARTNERSHIP"),
    
    GENERAL_PARTNERSHIP("GENERAL_PARTNERSHIP"),
    
    REGISTERED_SOLE_TRADER("REGISTERED_SOLE_TRADER"),
    
    SOLE_TRADER("SOLE_TRADER"),
    
    CIVIL_LAW_PARTNERSHIP("CIVIL_LAW_PARTNERSHIP"),
    
    PUBLIC_INSTITUTION("PUBLIC_INSTITUTION"),
    
    OTHER("OTHER");

    private String value;

    OrganizationEntityTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OrganizationEntityTypeEnum fromValue(String value) {
      for (OrganizationEntityTypeEnum b : OrganizationEntityTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<OrganizationEntityTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OrganizationEntityTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OrganizationEntityTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return OrganizationEntityTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_ORGANIZATION_ENTITY_TYPE = "organization_entity_type";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_ENTITY_TYPE)
  private OrganizationEntityTypeEnum organizationEntityType;

  public static final String SERIALIZED_NAME_ORGANIZATION_REGISTRATION_ID = "organization_registration_id";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_REGISTRATION_ID)
  private String organizationRegistrationId;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_VAT_ID = "vat_id";
  @SerializedName(SERIALIZED_NAME_VAT_ID)
  private String vatId;

  public Customer() {
  }

  public Customer title(String title) {
    
    
    
    
    this.title = title;
    return this;
  }

   /**
   * Customer’s Title. Allowed values per country: UK - \&quot;Mr\&quot;, \&quot;Ms\&quot; DE - \&quot;Herr\&quot;, \&quot;Frau\&quot; AT: \&quot;Herr, \&quot;Frau\&quot; CH: de-CH: \&quot;Herr, \&quot;Frau\&quot; it-CH: \&quot;Sig.\&quot;, \&quot;Sig.ra\&quot; fr-CH: \&quot;M\&quot;, \&quot;Mme\&quot;  BE: \&quot;Dhr.\&quot;, \&quot;Mevr.\&quot; NL: \&quot;Dhr.\&quot;, \&quot;Mevr.\&quot;
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Mr.", value = "Customer’s Title. Allowed values per country: UK - \"Mr\", \"Ms\" DE - \"Herr\", \"Frau\" AT: \"Herr, \"Frau\" CH: de-CH: \"Herr, \"Frau\" it-CH: \"Sig.\", \"Sig.ra\" fr-CH: \"M\", \"Mme\"  BE: \"Dhr.\", \"Mevr.\" NL: \"Dhr.\", \"Mevr.\"")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    
    
    
    this.title = title;
  }


  public Customer dateOfBirth(String dateOfBirth) {
    
    
    
    
    this.dateOfBirth = dateOfBirth;
    return this;
  }

   /**
   * Customer’s date of birth. The format is ‘yyyy-mm-dd’
   * @return dateOfBirth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1978-12-31", value = "Customer’s date of birth. The format is ‘yyyy-mm-dd’")

  public String getDateOfBirth() {
    return dateOfBirth;
  }


  public void setDateOfBirth(String dateOfBirth) {
    
    
    
    this.dateOfBirth = dateOfBirth;
  }


  public Customer gender(String gender) {
    
    
    
    
    this.gender = gender;
    return this;
  }

   /**
   * Customer’s gender - ‘male’ or ‘female’
   * @return gender
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "male", value = "Customer’s gender - ‘male’ or ‘female’")

  public String getGender() {
    return gender;
  }


  public void setGender(String gender) {
    
    
    
    this.gender = gender;
  }


  public Customer lastFourSsn(String lastFourSsn) {
    
    
    
    
    this.lastFourSsn = lastFourSsn;
    return this;
  }

   /**
   * Last four digits of the customer&#39;s social security number. This value is available for US customers.
   * @return lastFourSsn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Last four digits of the customer's social security number. This value is available for US customers.")

  public String getLastFourSsn() {
    return lastFourSsn;
  }


  public void setLastFourSsn(String lastFourSsn) {
    
    
    
    this.lastFourSsn = lastFourSsn;
  }


  public Customer nationalIdentificationNumber(String nationalIdentificationNumber) {
    
    
    
    
    this.nationalIdentificationNumber = nationalIdentificationNumber;
    return this;
  }

   /**
   * The customer&#39;s national identification number. This value is available for EU customers utilizing national identification numbers.
   * @return nationalIdentificationNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The customer's national identification number. This value is available for EU customers utilizing national identification numbers.")

  public String getNationalIdentificationNumber() {
    return nationalIdentificationNumber;
  }


  public void setNationalIdentificationNumber(String nationalIdentificationNumber) {
    
    
    
    this.nationalIdentificationNumber = nationalIdentificationNumber;
  }


  public Customer organizationEntityType(OrganizationEntityTypeEnum organizationEntityType) {
    
    
    
    
    this.organizationEntityType = organizationEntityType;
    return this;
  }

   /**
   * Organization entity type. Only applicable for B2B customers.
   * @return organizationEntityType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Organization entity type. Only applicable for B2B customers.")

  public OrganizationEntityTypeEnum getOrganizationEntityType() {
    return organizationEntityType;
  }


  public void setOrganizationEntityType(OrganizationEntityTypeEnum organizationEntityType) {
    
    
    
    this.organizationEntityType = organizationEntityType;
  }


  public Customer organizationRegistrationId(String organizationRegistrationId) {
    
    
    
    
    this.organizationRegistrationId = organizationRegistrationId;
    return this;
  }

   /**
   * Organization registration id. Only applicable for B2B customers.
   * @return organizationRegistrationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Organization registration id. Only applicable for B2B customers.")

  public String getOrganizationRegistrationId() {
    return organizationRegistrationId;
  }


  public void setOrganizationRegistrationId(String organizationRegistrationId) {
    
    
    
    this.organizationRegistrationId = organizationRegistrationId;
  }


  public Customer type(String type) {
    
    
    
    
    this.type = type;
    return this;
  }

   /**
   * Type of customer in the session. If nothing is added, a B2C session will be the default. If it is a b2b-session, you should enter organization to trigger a B2B session.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "organization", value = "Type of customer in the session. If nothing is added, a B2C session will be the default. If it is a b2b-session, you should enter organization to trigger a B2B session.")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    
    
    
    this.type = type;
  }


  public Customer vatId(String vatId) {
    
    
    
    
    this.vatId = vatId;
    return this;
  }

   /**
   * VAT ID. Only applicable for B2B customers.
   * @return vatId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "VAT ID. Only applicable for B2B customers.")

  public String getVatId() {
    return vatId;
  }


  public void setVatId(String vatId) {
    
    
    
    this.vatId = vatId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Customer instance itself
   */
  public Customer putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return Objects.equals(this.title, customer.title) &&
        Objects.equals(this.dateOfBirth, customer.dateOfBirth) &&
        Objects.equals(this.gender, customer.gender) &&
        Objects.equals(this.lastFourSsn, customer.lastFourSsn) &&
        Objects.equals(this.nationalIdentificationNumber, customer.nationalIdentificationNumber) &&
        Objects.equals(this.organizationEntityType, customer.organizationEntityType) &&
        Objects.equals(this.organizationRegistrationId, customer.organizationRegistrationId) &&
        Objects.equals(this.type, customer.type) &&
        Objects.equals(this.vatId, customer.vatId)&&
        Objects.equals(this.additionalProperties, customer.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, dateOfBirth, gender, lastFourSsn, nationalIdentificationNumber, organizationEntityType, organizationRegistrationId, type, vatId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    lastFourSsn: ").append(toIndentedString(lastFourSsn)).append("\n");
    sb.append("    nationalIdentificationNumber: ").append(toIndentedString(nationalIdentificationNumber)).append("\n");
    sb.append("    organizationEntityType: ").append(toIndentedString(organizationEntityType)).append("\n");
    sb.append("    organizationRegistrationId: ").append(toIndentedString(organizationRegistrationId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    vatId: ").append(toIndentedString(vatId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("title");
    openapiFields.add("date_of_birth");
    openapiFields.add("gender");
    openapiFields.add("last_four_ssn");
    openapiFields.add("national_identification_number");
    openapiFields.add("organization_entity_type");
    openapiFields.add("organization_registration_id");
    openapiFields.add("type");
    openapiFields.add("vat_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Customer
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Customer.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Customer is not found in the empty JSON string", Customer.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("title") != null && !jsonObj.get("title").isJsonNull()) && !jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("date_of_birth") != null && !jsonObj.get("date_of_birth").isJsonNull()) && !jsonObj.get("date_of_birth").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `date_of_birth` to be a primitive type in the JSON string but got `%s`", jsonObj.get("date_of_birth").toString()));
      }
      if ((jsonObj.get("gender") != null && !jsonObj.get("gender").isJsonNull()) && !jsonObj.get("gender").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `gender` to be a primitive type in the JSON string but got `%s`", jsonObj.get("gender").toString()));
      }
      if ((jsonObj.get("last_four_ssn") != null && !jsonObj.get("last_four_ssn").isJsonNull()) && !jsonObj.get("last_four_ssn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_four_ssn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_four_ssn").toString()));
      }
      if ((jsonObj.get("national_identification_number") != null && !jsonObj.get("national_identification_number").isJsonNull()) && !jsonObj.get("national_identification_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `national_identification_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("national_identification_number").toString()));
      }
      if ((jsonObj.get("organization_entity_type") != null && !jsonObj.get("organization_entity_type").isJsonNull()) && !jsonObj.get("organization_entity_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `organization_entity_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organization_entity_type").toString()));
      }
      if ((jsonObj.get("organization_registration_id") != null && !jsonObj.get("organization_registration_id").isJsonNull()) && !jsonObj.get("organization_registration_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `organization_registration_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("organization_registration_id").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("vat_id") != null && !jsonObj.get("vat_id").isJsonNull()) && !jsonObj.get("vat_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vat_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vat_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Customer.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Customer' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Customer> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Customer.class));

       return (TypeAdapter<T>) new TypeAdapter<Customer>() {
           @Override
           public void write(JsonWriter out, Customer value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Customer read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Customer instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Customer given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Customer
  * @throws IOException if the JSON string is invalid with respect to Customer
  */
  public static Customer fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Customer.class);
  }

 /**
  * Convert an instance of Customer to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

